### ISSUE TITLE
维基百科搜索不到相关信息

### ISSUE THREAD

**Issue by TanGuangZhi** [Spehhhhh/IADB_Scholar#1]
第31位学者[‪Xiaoping Zhang, MD, PhD‬ - ‪Google 学术搜索‬](https://scholar.google.com/citations?user=Vjrbf0IAAAAJ)按照“Xiaoping Zhang, MD, PhD”与“Xiaoping Zhang”都没搜到正确的维基百科内容？是关键词有问题吗？还有别的方案吗

**Comment by ipruning** [comment]
如果是在定位不到维基百科，就留空吧 😂
