### ISSUE TITLE
关于搜索流程的优化讨论

### ISSUE THREAD

**Issue by TanGuangZhi** [Spehhhhh/IADB_Scholar#2]
# 搜索流程

|      | 搜索步骤                                                     | 截图                                                         |
| ---- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 1    | 从下面获得H指数大于100的学者，选取一个开始搜索<br/>[Highly Cited Researchers (h>100) ](https://www.webometrics.info/en/hlargerthan100) | ![image-20210427182003330](http://picbed.tgz666.top/20210427182003.png) |
| 2    | 在谷歌学术搜索<br/>[‪AS Fauci‬ - ‪Google 学术搜索‬](https://scholar.google.com/citations?user=0dDO3SAAAAAJ) | ![image-20210427182033975](http://picbed.tgz666.top/20210427182034.png) |
| 3    | 在维基百科搜素<br/>[Anthony Fauci - Wikipedia](https://en.wikipedia.org/wiki/Anthony_Fauci) | ![image-20210427182043679](http://picbed.tgz666.top/20210427182043.png) |
| 4    | 通过谷歌搜索，找到其他信息，如学者官网等<br/>[AS Fauci - Google 搜索](https://www.google.com.hk/search?q=AS+Fauci&newwindow=1&safe=strict&source=hp&ei=GsSHYNTdGMu9hwOckoBQ&iflsig=AINFCbYAAAAAYIfSKuMRfx5Bj-ENfcbAOuq4FKsWOOYJ&oq=AS+Fauci&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMggIABAIEAoQHlDEBljEBmDsCmgBcAB4AIABW4gBW5IBATGYAQCgAQKgAQGqAQdnd3Mtd2l6sAEA&sclient=gws-wiz&ved=0ahUKEwjU0q-A-p3wAhXL3mEKHRwJAAoQ4dUDCAc&uact=5) | ![image-20210427182107636](http://picbed.tgz666.top/20210427182107.png) |
| 5    | 通过Acemap搜索获得作者合作网络图<br/> [Anthony S. Fauci - Acemap](https://www.acemap.info/authorDetail/1313399659) | ![image-20210427182118889](http://picbed.tgz666.top/20210427182118.png) |

# TODO与待优化
* 高引文章，高引论文上述流程无法搜索到，有什么好的办法吗？比如wos？
* 高引文章取谷歌学术里排名前几的可以吗？
* 部分学者acemap中查不到作者关系图，还有别的办法吗？

# 总结
* 不纠结于某些自己难以解决没有思路的东西，先完成基础的，剩下通过提问大佬来找解决办法
* 需要沉淀出更多信息源，应该每个信息的查询都要有2个以上不同的信息源来进行交叉验证或者补充

# ChangeLog
* **V0.0.0 m** 2021-04-27 Tue

**Comment by ipruning** [comment]
- 待优化点总结的很好，之后我看看用 Airtable API 能不能简化一下。
- 作者关系图除了 Acemap 外其实还有很多工具，这周学习学术章节的时候可以 👀 留意一下，我先不剧透了。

PS：你能申请 Airtable API Key 么？

**Comment by LXY-888** [comment]
WOS有作者检索，可以与https://www.aminer.cn/search/person?t=b&q=Graham%20Colditz和谷歌学术相互印证，有个疑问，作者关系图怎么样集合到airtable，alex？
